package uagrm.inf310sb.principal;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import uagrm.inf310sb.ejecutador.Ejecutor;

/**
 *
 * @author GERSON
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private String opcionMenu;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        this.setLocationRelativeTo(this);
        
        this.setImagenLabel(this.etiquetaImagen, "src/imagenes/mapa dijkstra.jpg");
        this.opcionMenu = "Dijkstra";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaImagen = new javax.swing.JLabel();
        etiquetaPartida = new javax.swing.JLabel();
        cajaPartida = new javax.swing.JComboBox<>();
        etiquetaLlegada = new javax.swing.JLabel();
        cajaLlegada = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlgoritmo = new javax.swing.JMenu();
        dijkstra = new javax.swing.JMenuItem();
        ordenTopol = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaPartida.setText("Punto de Partida");

        cajaPartida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Santa Cruz", "Trinidad", "Tarija", "Cochabamba", "Sucre", "Potosi", "Oruro", "La Paz", "Cobija" }));
        cajaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaPartidaActionPerformed(evt);
            }
        });

        etiquetaLlegada.setText("Punto de Llegada");

        cajaLlegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Santa Cruz", "Trinidad", "Tarija", "Cochabamba", "Sucre", "Potosi", "Oruro", "La Paz", "Cobija" }));
        cajaLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaLlegadaActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar camino mas barato");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        menuAlgoritmo.setText("Algortimos");

        dijkstra.setText("Dijkstra");
        dijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dijkstraActionPerformed(evt);
            }
        });
        menuAlgoritmo.add(dijkstra);

        ordenTopol.setText("Ordenamiento Topologico");
        ordenTopol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenTopolActionPerformed(evt);
            }
        });
        menuAlgoritmo.add(ordenTopol);

        jMenuItem1.setText("Prim");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAlgoritmo.add(jMenuItem1);

        jMenuItem2.setText("Kruskal 1");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuAlgoritmo.add(jMenuItem2);

        jMenuItem3.setText("Kruskal 2");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuAlgoritmo.add(jMenuItem3);

        jMenuBar1.add(menuAlgoritmo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(etiquetaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(etiquetaPartida)
                                    .addComponent(cajaPartida, 0, 117, Short.MAX_VALUE)
                                    .addComponent(etiquetaLlegada)
                                    .addComponent(cajaLlegada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(etiquetaPartida)
                .addGap(18, 18, 18)
                .addComponent(cajaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaLlegada)
                .addGap(18, 18, 18)
                .addComponent(cajaLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
            .addComponent(etiquetaImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaLlegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaLlegadaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch (this.opcionMenu) {
            case "Dijkstra": {
                int posOrigen = this.cajaPartida.getSelectedIndex();
                int posDestino = this.cajaLlegada.getSelectedIndex();
            
                if (posOrigen == posDestino) {
                    //error
                } else {
                    String camino = Ejecutor.ejecutarDijkstra(posOrigen, posDestino);
                    this.jTextArea1.setText(camino);
                }
            } break;
            
            case "Ordenamiento Topologico": {
                String orden = Ejecutor.ejecutarOrdenTopologico();
                
                this.jTextArea1.setText(orden);
            } break;
            
            case "Prim": {
                String vertice = JOptionPane.showInputDialog("Ingrese el vertice de inicio");
                
                if (vertice == null)
                    return;
                
                if (vertice.compareTo("") == 0) {
                    JOptionPane.showMessageDialog(null, "Dato vacio", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                if (!esNumero(vertice)) {
                    JOptionPane.showMessageDialog(null, "El dato no es numero", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                int nroVertice = Integer.parseInt(vertice);
                String lista = Ejecutor.ejecutarPrim(nroVertice);
                this.setImagenLabel(etiquetaImagen, "src/imagenes/prim01.png");
                this.jTextArea1.setText(lista);
            } break;
            
            case "Kruskal 1": {
                String lista = Ejecutor.ejecutarKruskal1();
                this.setImagenLabel(etiquetaImagen, "src/imagenes/kruskal01.jpg");
                this.jTextArea1.setText(lista);
            } break;
            
            case "Kruskal 2": {
                String lista = Ejecutor.ejecutarKruskal2();
                this.setImagenLabel(etiquetaImagen, "src/imagenes/kruskal11.jpg");
                this.jTextArea1.setText(lista);
            } break;
            default:
                throw new AssertionError();
        }        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cajaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaPartidaActionPerformed

    private void dijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dijkstraActionPerformed
        this.setImagenLabel(this.etiquetaImagen, "src/imagenes/mapa dijkstra.jpg");
        
        this.etiquetaPartida.setVisible(true);
        this.etiquetaLlegada.setVisible(true);
        this.cajaPartida.setVisible(true);
        this.cajaLlegada.setVisible(true);
        this.jButton1.setText("Buscar camino mas barato");
        this.opcionMenu = evt.getActionCommand();
        this.jTextArea1.setText("");
    }//GEN-LAST:event_dijkstraActionPerformed

    private void ordenTopolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenTopolActionPerformed
        this.setImagenLabel(etiquetaImagen, "src/imagenes/diagrama pert.jpg");
//        ImageIcon imagen = new ImageIcon("src/imagenes/diagrama pert.jpg");
//        
//        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(560,
//            400, Image.SCALE_DEFAULT));
//        
//        this.etiquetaImagen.setIcon(icono);
//        this.repaint();
        
        this.etiquetaPartida.setVisible(false);
        this.etiquetaLlegada.setVisible(false);
        this.cajaPartida.setVisible(false);
        this.cajaLlegada.setVisible(false);
        this.jButton1.setText("Orden de tareas");
        this.opcionMenu = evt.getActionCommand();
        this.jTextArea1.setText("");
    }//GEN-LAST:event_ordenTopolActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setImagenLabel(etiquetaImagen, "src/imagenes/prim0.png");
        
        this.etiquetaPartida.setVisible(false);
        this.etiquetaLlegada.setVisible(false);
        this.cajaPartida.setVisible(false);
        this.cajaLlegada.setVisible(false);     
        this.jButton1.setText("Arbol costo minimo");
        this.opcionMenu = evt.getActionCommand();
        this.jTextArea1.setText("");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setImagenLabel(etiquetaImagen, "src/imagenes/kruskal0.jpg");
        
        this.etiquetaPartida.setVisible(false);
        this.etiquetaLlegada.setVisible(false);
        this.cajaPartida.setVisible(false);
        this.cajaLlegada.setVisible(false);     
        this.jButton1.setText("Arbol costo minimo");
        this.opcionMenu = evt.getActionCommand();
        this.jTextArea1.setText("");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.setImagenLabel(etiquetaImagen, "src/imagenes/kruskal1.jpg");
        
        this.etiquetaPartida.setVisible(false);
        this.etiquetaLlegada.setVisible(false);
        this.cajaPartida.setVisible(false);
        this.cajaLlegada.setVisible(false);     
        this.jButton1.setText("Arbol costo minimo");
        this.opcionMenu = evt.getActionCommand();
        this.jTextArea1.setText("");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    private void setImagenLabel(JLabel labelName, String root) {
        ImageIcon imagen = new ImageIcon(root);
        
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(labelName.getWidth(),
                labelName.getHeight(), Image.SCALE_DEFAULT));
        
        labelName.setIcon(icono);
        this.repaint();
    }
    
    private boolean esNumero(String numero) {
        try {
            Integer.valueOf(numero);
        } catch (NumberFormatException e) {
            return false;
        }
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cajaLlegada;
    private javax.swing.JComboBox<String> cajaPartida;
    private javax.swing.JMenuItem dijkstra;
    private javax.swing.JLabel etiquetaImagen;
    private javax.swing.JLabel etiquetaLlegada;
    private javax.swing.JLabel etiquetaPartida;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu menuAlgoritmo;
    private javax.swing.JMenuItem ordenTopol;
    // End of variables declaration//GEN-END:variables
}
